#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

/usr/bin/osascript $DIR/skype_status_online
$DIR/timestamp_start
$DIR/tunnels_open && /usr/bin/osascript $DIR/skype_status_online
exit
